### ISSUE TITLE
lxq remove not work properly

### ISSUE THREAD

**Issue by tannoiser** [aaronstuder/lxq#10]
Hi Aaron.

It seems to me that lxq remove is broken for installed on host kind of apps.

I installed cockpit but remove won't work:

root@lxd-server:~# lxq remove cockpit
ERROR: cockpit not found

I can fix my installation following and reversing the command in /opt/lxq/apps/cockpit/cockpit.install but it's not so comfortable.

**Comment by X1Aaron** [comment]
This is because there is no container called cockpit - this is normal. You can just disregaud.
